### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jensens** [plone/plone.patternslib#16]
May we have a release? The latest on PyPI is kind of broken in a current Plone 5.

**Comment by agitator** [comment]
should https://github.com/plone/plone.patternslib/pull/12 be merged then?

**Comment by jensens** [comment]
@agitator it think if the missing changelog entry is added it can be merged.

**Comment by pilz** [comment]
@jensens I am completely swamped, but I gave you rights on pypi, feel free to push a release.

**Comment by jensens** [comment]
@pilz thanks!

@thet is #12 ok for merge? I am a bit lost with the details.

**Comment by thet** [comment]
@jensens , branch #12 is working quite well and proved in production. the only thing which I'm uneasy with merging #12 is, that it uses an unmerged branch of Patternslib - this is the PR: https://github.com/Patternslib/Patterns/pull/480
this PR is failing for a unknown reason, which does not seem related to my changes...

**Comment by thet** [comment]
oh-oh I just re-triggered a travis rebuild of Patternslib/Patterns#480 and it's passing! without any changes, I love it.

**Comment by thet** [comment]
@jensens i'd wait for the merge of  Patternslib/Patterns#480 - if it will be merged. than the patternslib installation of plone.patternslib should be updated, IMO.

**Comment by thet** [comment]
@jensens @agitator plone.patternslib is now ready to be released. I've merged my branch with it's massive changes due to a general resource update.

**Comment by jensens** [comment]
Release as 1.0 done!
