### ISSUE TITLE
pat-inject target: self becomes a link

### ISSUE THREAD

**Issue by espenmn** [plone/plone.patternslib#17]
<a  href="/path/to/table" class="pat-inject" data-pat-inject="target: self;  trigger: autoload; source: #content-core">tabell 158</a>

Works, but but the contents becomes a link.

I have tried to use <div> and data-pat-inject="url: /path/to/table" 

Is there a way to replace 'self', without becoming a link, or can that only be done by using another target ?

**Comment by petschki** [comment]
I recommend filing an issue/question here: https://github.com/Patternslib/Patterns/issues ... note: this package is obsolete since Plone 6
