### ISSUE TITLE
Some tile providers for pat-leaflet cannot be registered

### ISSUE THREAD

**Issue by pbauer** [plone/plone.patternslib#24]
Some tile providers need more than their name to be registered. E.g.
`L.tileLayer.provider('MapBox', {id: 'mapbox.streets', accessToken: 'xxx'}).addTo(map);` 
See https://github.com/leaflet-extras/leaflet-providers#providers-requiring-registration

Currently it is not possible to use such layers with pat-leaflet. Could we change the pattern to allow passing that additional layer-information as configuration?

**Comment by thet** [comment]
Fixed via: https://github.com/Patternslib/pat-leaflet/pull/2
