### ISSUE TITLE
Status of pat-gallery

### ISSUE THREAD

**Issue by ezvirtual** [plone/plone.patternslib#27]
Hi there,
I was hoping that someone could shed some insight into the status of the patternslib gallery:

- Does it work?
- If not, what kind of attention does it require?
- If it does, how to do I use it?

Thanks in advance for any assistance you can provide.

**Comment by thet** [comment]
I use it. It's based on http://photoswipe.com/

You have to install plone.patternslib to install the resource definitions.
Then include the pattern JS + LESS in your bundle:

your custom bundle JS:
```
require([
  'jquery',
  'pat-registry',
  'pat-gallery'
], function($, registry) {
    if (window.parent === window) {
        $(document).ready(function() {
            if (!registry.initialized) {
                registry.init();
            }
        });
    }
});
```

And in your custom bundle LESS:
```
@import (less) "@{photoswipe-ui}";
@import (less) "@{photoswipe}";
```

And use it in your template:
```
<div class="pat-gallery">
  <figure tal:repeat="item view/results">
    <a href="${item/url}">
      <img tal:replace="structure item/imagetag" />
    </a>
  </figure>
</div>
```

That's it, basically.

Also see: https://github.com/Patternslib/Patterns/blob/master/src/pat/gallery/documentation.md

**Comment by ezvirtual** [comment]
Nice one, thank you very much for that assistance :)
