### ISSUE TITLE
Alpha or beta release?

### ISSUE THREAD

**Issue by jensens** [plone/plone.patternslib#3]
What about some alpha or beta release? Cant be wrong :)

**Comment by agitator** [comment]
release?

**Comment by agitator** [comment]
and please update this package from https://github.com/patternslib/patterns

**Comment by jcbrand** [comment]
The patternslib version in this package is a bit older than master. There are some new fixes in master, and I have another bugfix lined up. I'll then make a new patternslib release. I'd suggest holding off releasing this until then.

**Comment by jcbrand** [comment]
I've released Patternslib 2.0.13 and now made an initial release of plone.patternslib (version 0.1).

**Comment by jcbrand** [comment]
And now I had to release 0.2 of plone.patternslib because I noticed that I had lost a polyfill during a merge conflict. Sorry about that.
