### ISSUE TITLE
New release 1.1.0

### ISSUE THREAD

**Issue by petschki** [plone/plone.patternslib#33]
since there is Python 3 support and some other features I ask for a `1.1.0` release

@plone/release-team

**Comment by mauritsvanrees** [comment]
`plone.patternslib` is not used in core Plone, and the release team has no PyPI rights on it.
At https://pypi.org/project/plone.patternslib/ I see as maintainers @jcbrand @jensens @pilz @thet and @pysailor. Can one of you make a 1.1.0 release?
Might be good to add `plone` to the PyPI maintainers too.

**Comment by jensens** [comment]
released 1.1.0

**Comment by pysailor** [comment]
Hi @mauritsvanrees,
I added `plone` as maintainer on pypi
