### ISSUE TITLE
Files mentioned in registry are missing in fs

### ISSUE THREAD

**Issue by jensens** [plone/plone.patternslib#4]
@jcbrand There are files in FS missing that are mentioned in FS. I commented them in registry.xml in commit 16f2ee4, now `plone-compile-resources` works again (to some degree, other problem unrelated here).

I'm pretty sure that this is not intended, but due to lack of knowledge I don't know how to fix this.

**Comment by jcbrand** [comment]
Hi @jensens, as the comments says above, ` <!-- patternslib dependencies fetched by Bower -->`.

To get the bower dependencies you need to `cd` into `components/patternslib` and then run
 `bower install` or better yet `make stamp-bower.

I understand that this is not clear however, should it perhaps be added as a comment?

**Comment by jensens** [comment]
Ok. Half of it is in there, the other part is fetched by bower? This is confusing.

The problem here is, if I use plone.patternslib (anywhere, i.e. as dependencu of an addon) I have to run bower deep in plone.patternslib there before I can do a `bin/plone-compile-resources` - otherwise the resources are missing and the compile fails/aborts. This would be necessary even if I use plone.patternslib as an egg and any other - unrelated - addon need a compile.

**Comment by jensens** [comment]
@jcbrand probably the repository is not complete? In whole `devsrc/plone.patternslib/src/plone/patternslib/static/components/patternslib` there is no `bower.json` nor  a `Makefile`.

**Comment by jcbrand** [comment]
Sorry, my memory is a bit fuzzy and I think I led you down the wrong path @jensens.

I think @pilz should be better able to help you here. They are using this library in production.

I haven't done much with it and haven't worked on any Plone stuff since the Bucharest.

**Comment by pilz** [comment]
Sorry for replying to sluggishly. I will have to look into this with my full brain I fear. @jensens could you quickly tell me what you did to find out of this? What led you into an error?

**Comment by jensens** [comment]
in 16f2ee4e0d6c83bb9b9f3c3919fa3d219847a455 I commented a bunch of files that are registered in registry.xml but are not in the filesystem. So far all works without these files - for us. But someone with more insight into plone.patternslib should have a look and decide if this are just leftovers or important things.

**Comment by pilz** [comment]
So you pulled the plone.patternslib egg into a plone installation and it complained about these missing files? I'll start then to compare why it worked here.

**Comment by jensens** [comment]
well, as a develop egg and then I compiled resources for my project and then it complained as a side effect. but dont ask me details, its been a while now.

**Comment by pilz** [comment]
Thanks! I'll try that path.
