### ISSUE TITLE
bower.json instead makefile

### ISSUE THREAD

**Issue by thet** [plone/plone.patternslib#5]
any reason why not to use bower instead of the makefile?

I'm about to create a pull request with another externally living pattern - pat-leaflet.

IMO, it would be easier to use bower to manage resources.

Anything aginast, if I create such a pull request?

/cc @jcbrand

**Comment by jcbrand** [comment]
We use bower to manage dependencies. The Makefile is just used to call bower.

**Comment by thet** [comment]
I would use bower to download patternslib, and possibly other patternslib add-ons. It would do the same, but IMO with a simpler setup. Also, it makes it easier to add extra patterns by just configuring bower.json.

So, before I go the wrong way, would you accept a PR which:
- removes the Makefile and uses a bower.json and .bowerrc (to set the path to src/plone.patternslib/static/components)?
- adds pat-leaflet (in a seperate PR and after last remaining issues with it are resolved)

?

The second task - adding pat-leaflet - is the reason why I would do the first one (bower).

**Comment by thet** [comment]
I see, the current resources in components are less than 2 MB alltogether, due to the .gitignore file with lots of ignores. The full bower_components without that .gitignore in place is around 40 to 50 MB.

I remember a discussion where I mentioned my concerns about the size of patternslib and if we really want to include that in CMFPlone. I think that doesn't really apply to plone.patternslib, as it's optional. Due to easier maintainability, I'll remove the .gitignore file in my PR.

**Comment by jcbrand** [comment]
Sounds good to me. ping @pilz and @pysailor

**Comment by pilz** [comment]
Wouldn't that mean that the egg may get bloated a lot with fetched dependencies? I agree with the maintainability, but if the egg gets 50M in size, that sounds like a hazzle. Will that be the case?

**Comment by thet** [comment]
@pilz yes, it will ... but I think giving up the .gitignore file would be much easier for maintenance. currently some resources are not found and I suspect the .gitignore file responsible for that.

I'll try out a simpler .gitignore to exclude all *.jpg *.zip *.map, maybe also *.min.js|css and others...

**Comment by pilz** [comment]
You could even go for the bower_components and everything that is *psd. I think that are the biggies :)

> Am 10.06.2016 um 11:53 schrieb Johannes Raggam <notifications@github.com>:
> 
> @pilz <https://github.com/pilz> yes, it will ... but I think giving up the .gitignore file would be much easier for maintenance. currently some resources are not found and I suspect the .gitignore file responsible for that.
> 
> I'll try out a simpler .gitignore to exclude all *.jpg *.zip *.map, maybe also *.min.js|css and others...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/plone/plone.patternslib/issues/5#issuecomment-225141892>, or mute the thread <https://github.com/notifications/unsubscribe/AAIemo9aUBcNdDowVGWzJPeQvPqrMVtGks5qKTP9gaJpZM4Ix7-D>.
> 


--
SYSLAB.COM GmbH, Landwehrstraße 60-62, 80336 Munich, Germany, Amtsgericht Muenchen, HRB 135057, Gabriele Loher, Alexander Pilz - Tel: +49 (0) 89 306 35 89 0

**Comment by thet** [comment]
Done by: https://github.com/plone/plone.patternslib/pull/6
